name: Preview Vercel
on: [pull_request]
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install
        run: pnpm install
      - name: Deploy to Vercel (if secrets)
        if: ${{ secrets.VERCEL_TOKEN != '' }}
        run: |
          npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
